import type { Metadata } from 'next';
import { ArrowRightIcon, CheckIcon, SparklesIcon } from '@/components/icons';
import { ProviderLogo } from '@/components/provider-logo';
import { SiteFrame } from '@/components/site-frame';
import { getPageMeta } from '@/data/content';
import { providerAvailabilityCheckedAt, providerDisplayStatus } from '@/data/provider-availability';
import { codexProviderConfig as codex, codexStartCommand } from '@/data/codex-example';

const fallbackPage = getPageMeta('/vibe-coding');
const fallbackMetadata: Metadata = { title: fallbackPage?.title ?? 'Coding-agent setup', description: 'Status-marked kineticRouter setup references for Codex and Claude Code.' };

export const metadata = fallbackMetadata;
const setup = `export KINETICROUTER_API_KEY="YOUR_KINETICROUTER_API_KEY"`;

export default function VibeCodingPage() {
  const openAiStatus = providerDisplayStatus('openai');
  const anthropicStatus = providerDisplayStatus('anthropic');
  const grokStatus = providerDisplayStatus('grok');
  return <SiteFrame>
    <section className="hero-grid hero-glow relative overflow-hidden border-b border-border pb-14 pt-10 text-center md:pb-16 md:pt-14"><div className="relative z-10 mx-auto max-w-4xl px-4"><div className="inline-flex items-center gap-2 rounded-full border border-[var(--brand-soft-border)] bg-[var(--brand-soft-bg)] px-4 py-1.5 text-[10px] text-primary"><ProviderLogo provider="openai" className="h-3.5 w-3.5" /> {openAiStatus.protocolLabel} · {openAiStatus.badgeLabel} · account testing required</div><h1 className="mt-5 text-4xl font-semibold tracking-[-.045em] md:text-[3.5rem]">Configure coding agents<br />with route status visible</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-muted-foreground">Start with the OpenAI-compatible base URL. Claude Code remains a {anthropicStatus.badgeLabel.toLowerCase()} native-route integration and is intentionally not presented as ready today.</p><div className="mt-7 flex justify-center gap-3"><a href="/account/sign-in" className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-white">Get API Key <ArrowRightIcon className="h-4 w-4" /></a><a href="/docs/integrations/codex" className="rounded-lg border border-primary px-6 py-3 text-sm font-semibold text-primary">Read {openAiStatus.badgeLabel.toLowerCase()} guide</a></div><div className="mx-auto mt-8 max-w-2xl overflow-hidden rounded-lg border border-border bg-[var(--terminal)] text-left shadow-2xl"><div className="flex items-center border-b border-border bg-[var(--code)] px-4 py-2.5 text-[11px] text-muted-foreground"><ProviderLogo provider="openai" className="mr-2 h-4 w-4" />Environment configuration</div><pre className="p-4 font-mono text-[11px] leading-6 text-[#dce2f8]"><code>{setup}</code></pre></div></div></section>
    <section className="bg-muted/20 py-14 md:py-20"><div className="page-container"><h2 className="text-center text-4xl font-semibold tracking-tight">What is actually documented</h2><p className="mx-auto mt-3 max-w-2xl text-center text-sm leading-7 text-muted-foreground">No universal throughput, latency, uptime, or rate-limit promise is made here. Those values depend on your account and deployment.</p><div className="mt-10 grid gap-3 md:grid-cols-3">{[
      ['OpenAI-compatible', 'Detected base route', 'The /v1 surface responds and is suitable for authenticated conformance testing.', 'Validate the exact model and feature you use'],
      ['Codex', `${openAiStatus.badgeLabel} integration guide`, 'Configure the Responses provider with an environment-held key, then verify your chosen model. Optional WebSocket behavior requires a separate account test.', 'Test with your kineticRouter account'],
      ['Claude Code', `${anthropicStatus.badgeLabel} native route`, 'The Anthropic-native path is not active, so copyable setup commands are withheld.', 'The roadmap remains visible without a false live claim'],
    ].map(([eyebrow, title, copy, foot], index) => { const status = index === 2 ? anthropicStatus : openAiStatus; return <article key={eyebrow} className="surface p-6"><div className="flex items-center"><ProviderLogo provider={index === 2 ? 'claude' : 'openai'} className="h-7 w-7" /><span className="ml-auto text-[8px] font-semibold tracking-wider text-muted-foreground">{status.badgeLabel.toUpperCase()}</span></div><p className="mt-5 text-[10px] font-semibold uppercase tracking-wider text-primary">{eyebrow}</p><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-4 text-xs leading-6 text-muted-foreground">{copy}</p><p className="mt-5 flex gap-2 border-t border-border pt-4 text-[10px] text-muted-foreground"><CheckIcon className="h-4 w-4 shrink-0 text-primary" />{foot}</p></article>; })}</div></div></section>
    <section className="page-container py-14 md:py-20"><p className="text-center text-xs font-semibold uppercase tracking-wider text-primary">Configuration reference</p><div className="mt-8 grid gap-4 lg:grid-cols-2"><article className="surface p-5"><div className="flex items-center gap-2"><ProviderLogo provider="openai" className="h-5 w-5" /><h2 className="text-base font-semibold">Codex</h2><span className="ml-auto rounded-full border border-border px-2 py-0.5 text-[8px] font-semibold tracking-wider text-muted-foreground">{openAiStatus.badgeLabel.toUpperCase()}</span></div><ol className="mt-4 flex flex-wrap gap-4">{['Set the API key environment variable', 'Merge the provider config', 'Select an available Responses model'].map((step, index) => <li key={step} className="flex items-center gap-2 text-[10px] text-muted-foreground"><span className="grid h-5 w-5 place-items-center rounded-full bg-muted text-foreground">{index + 1}</span>{step}</li>)}</ol><pre className="mt-5 min-h-44 overflow-auto rounded-lg bg-[var(--terminal)] p-4 font-mono text-[11px] leading-6 text-[#c8d1ff]"><code>{codex}</code></pre><pre className="mt-3 overflow-auto rounded-lg border border-border p-3 font-mono text-xs"><code>{codexStartCommand}</code></pre></article><article className="surface grid min-h-[280px] place-items-center p-8 text-center"><div><ProviderLogo provider="claude" className="mx-auto h-9 w-9" /><div className="mt-4 inline-flex rounded-full border border-border px-2 py-0.5 text-[8px] font-semibold tracking-wider text-muted-foreground">{anthropicStatus.badgeLabel.toUpperCase()}</div><h2 className="mt-3 text-lg font-semibold">Claude Code native setup</h2><p className="mx-auto mt-3 max-w-md text-xs leading-6 text-muted-foreground">Commands will appear after the Anthropic-native kineticRouter route is enabled and verified. The imported reference remains available in the status-marked docs.</p><a href="/docs/integrations/claude-code" className="mt-5 inline-flex text-xs font-semibold text-primary">View {anthropicStatus.badgeLabel.toLowerCase()} guide <ArrowRightIcon className="ml-1 h-4 w-4" /></a></div></article></div><div className="mt-10 grid grid-cols-2 overflow-hidden rounded-xl border border-border md:grid-cols-4">{[[providerAvailabilityCheckedAt, 'Last fact check'], [openAiStatus.badgeLabel, 'OpenAI route'], [anthropicStatus.badgeLabel, 'Anthropic route'], [grokStatus.badgeLabel, 'Grok route']].map(([value, label]) => <div key={label} className="border-b border-r border-border p-5 text-center"><strong className="block text-xl text-primary">{value}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{label}</span></div>)}</div></section>
    <section className="border-y border-border bg-muted/25 py-16 text-center"><SparklesIcon className="mx-auto h-8 w-8 text-primary" /><h2 className="mt-4 text-4xl font-semibold tracking-tight">Test the route you plan to ship</h2><p className="mx-auto mt-3 max-w-xl text-sm text-muted-foreground">Use the customer console for authoritative keys, balance, billing, and account capabilities.</p><a href="/account/sign-in" className="mt-7 inline-flex rounded-lg bg-primary px-7 py-3 text-sm font-semibold text-white">Open console</a></section>
  </SiteFrame>;
}
