import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { DocsShell } from '@/components/docs-shell';
import { docsRoutes, getDocsPage } from '@/data/content';
import { loadPublishedSiteContent, publishedDoc, publishedDocEntry, siteDocMarkdownToHtml } from '@/data/site-content';

type Props = { params: Promise<{ slug?: string[] }> };
function routeFrom(slug?: string[]) { return slug?.length ? `/docs/${slug.join('/')}` : '/docs'; }
export function generateStaticParams() { return [...docsRoutes.map((route) => ({ slug: route === '/docs' ? [] : route.replace('/docs/', '').split('/') })), { slug: ['en'] }]; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const requestedRoute = routeFrom(slug); const route = requestedRoute === '/docs/en' ? '/docs' : requestedRoute; const { meta, status } = getDocsPage(route); if (!meta) return {}; const siteContent = await loadPublishedSiteContent(); const entry = publishedDocEntry(siteContent, route); if (siteContent.docs.length && (!entry || !entry.enabled)) return { robots: { index: false, follow: false } }; const published = publishedDoc(siteContent, route); const baseTitle = published?.title ?? meta.title; const title = status.status === 'planned' ? `${baseTitle} (${status.label})` : baseTitle; const description = published?.description || `${status.summary} ${meta.description}`; return { title, description, alternates: { canonical: meta.canonical }, robots: status.status === 'planned' ? { index: false, follow: false } : undefined, openGraph: { type: 'website', url: meta.canonical, title, description, images: [] }, twitter: { card: 'summary', title, description, images: [] } }; }
export default async function DocsPage({ params }: Props) { const { slug } = await params; const requestedRoute = routeFrom(slug); const route = requestedRoute === '/docs/en' ? '/docs' : requestedRoute; const { meta, content, status } = getDocsPage(route); if (!meta || !content) notFound(); const siteContent = await loadPublishedSiteContent(); const entry = publishedDocEntry(siteContent, route); if (siteContent.docs.length && (!entry || !entry.enabled)) notFound(); const published = publishedDoc(siteContent, route); const html = published ? siteDocMarkdownToHtml(published) : content.html; return <DocsShell route={route} html={html} headings={published ? [published.title] : meta.headings} status={status} siteContent={siteContent} />; }
